services:
  - type: web
    name: hdfc-fleet-expres
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.5.0
